#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Stochastic-approximation (SPSA) version of example_pyomo.py.

The deterministic MIP in example_pyomo.py assumes the inflow Q_in is known in
advance. Here the inflow is random and autocorrelated, generated by an AR(1)
recursion on the log scale:

    Y_t = mu_Y + phi*(Y_{t-1} - mu_Y) + eps_t,   eps_t ~ N(0, sigma_eps^2)
    Q_in[t] = exp(Y_t)

so Q_in[t] is log-normal with E[Q_in[t]] = 5 m3/s (mu_Y is calibrated for
this), and we look for a fixed (here-and-now) pumping schedule Q_pump that
minimises

    E[ total pumped water  +  PENALTY * storage-bound violations ].

This expectation has no closed form, so the schedule is found with
Simultaneous Perturbation Stochastic Approximation (SPSA, Spall 1992):
every iteration draws a small batch of inflow realisations, estimates the
full 21-dimensional gradient from only TWO simulations of the water system
(at theta + c*Delta and theta - c*Delta, with common random numbers), and
takes a Robbins-Monro step - the same recursion as in
"HW5 - Question 1b.py", but with a vector-valued decision.

Modelling changes w.r.t. the MIP:
  * Q_pump is no longer a solver variable but the SA iterate theta.
  * The orifice is a rule-based recourse instead of a decision: it drains by
    gravity at full capacity whenever the storage level is above sea level.
    (That is what the MIP solution does anyway - gravity drainage is free -
    so the binary x[t] is replaced by the level comparison itself.)
  * The hard bounds 0 <= H_storage <= STORAGE_MAX become a penalty, because
    with random inflow a fixed schedule cannot guarantee them almost surely.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

SEED = 43

# ------------------------------------------------------------------
# 1. Data and physical constants (identical to example_pyomo.py)
# ------------------------------------------------------------------
BASE = '/Users/martijnkrikke/Documents/Scriptie/Scriptie_martijn'
time_series = pd.read_csv(f'{BASE}/timeseries_import.csv')

T = 21
H_sea = time_series["H_sea"].to_numpy()[:T]

STORAGE_MAX = 0.5
H_start = 0.4
A = 1e6
dt = 3600.0
PUMP_MAX = 7.0
ORIFICE_MAX = 10.0

w = 3.0   # m       width of orifice
d = 0.8   # m       height of orifice
C = 1.0   # none    orifice constant
g = 9.8   # m/s^2   gravitational acceleration

# ------------------------------------------------------------------
# 2. Stochastic inflow and the simulation model
# ------------------------------------------------------------------
PHI = 0.8                             # AR(1) persistence (log scale)
SIGMA_EPS = 0.3                       # innovation std (log scale)
Q_MEAN = 5.0                          # target E[Q_in[t]]
PENALTY = 1                      # violation water is 10x as expensive as pumped water

SIGMA_Y2 = SIGMA_EPS ** 2 / (1.0 - PHI ** 2)
MU_Y = np.log(Q_MEAN) - 0.5 * SIGMA_Y2


def sample_inflow(rng, n):
    """n inflow trajectories of length T from an AR(1) log-normal process.

    Y_t = mu_Y + phi*(Y_{t-1} - mu_Y) + eps_t,  eps_t ~ N(0, SIGMA_EPS^2),
    Q_in[t] = exp(Y_t), so E[Q_in[t]] = Q_MEAN (each trajectory starts at
    the stationary mean mu_Y).
    """
    Y = np.empty((n, T))
    Y[:, 0] = MU_Y
    eps = rng.normal(0.0, SIGMA_EPS, size=(n, T))
    for t in range(1, T):
        Y[:, t] = MU_Y + PHI * (Y[:, t - 1] - MU_Y) + eps[:, t]
    return np.exp(Y)


def simulate_storage(q_pump, q_in):
    """Storage levels H[0..T-1] for one inflow realisation and a fixed schedule.

    Same balance as the MIP:  A*(H[t] - H[t-1]) = dt*(Q_in - Q_pump - Q_orifice)
    at t-1. The orifice acts as recourse: full gravity capacity
    Q <= w*C*d*sqrt(2g(H - H_sea)) whenever H > H_sea, capped so the orifice
    itself cannot drain the storage below empty.
    """
    H = np.empty(T)
    q_ori = np.empty(T)
    H[0] = H_start
    for t in range(T):
        if t > 0:
            H[t] = H[t - 1] + dt / A * (q_in[t - 1] - q_pump[t - 1] - q_ori[t - 1])
        head = H[t] - H_sea[t]
        if head > 0.0:
            available = A / dt * H[t] + q_in[t] - q_pump[t]
            q_ori[t] = min(w * C * d * np.sqrt(2.0 * g * head),
                           ORIFICE_MAX,
                           max(available, 0.0))
        else:
            q_ori[t] = 0.0
    return H


def penalised_cost(q_pump, q_in):
    """Sample cost in flow units (m3/s summed over the horizon).

    Pumped-volume part equals the MIP objective divided by dt; the factor
    A/dt converts a level violation (m) into the equivalent flow that would
    have removed it, so PENALTY compares like with like.
    """
    H = simulate_storage(q_pump, q_in)
    violation = np.maximum(H - STORAGE_MAX, 0.0) + np.maximum(-H, 0.0)
    return np.sum(q_pump) + PENALTY * A / dt * np.sum(violation)


# ------------------------------------------------------------------
# 3. SPSA
# ------------------------------------------------------------------
N_ITER = 60000
SPSA_a = 0.1          # step-size numerator      a_k = a / (k+1+A_stab)^0.602
SPSA_c = 0.9          # perturbation numerator   c_k = c / (k+1)^0.101
SPSA_A = 0.1 * N_ITER # stability constant (Spall's ~10% rule)
ALPHA, GAMMA = 0.602, 0.101
AVG_FRAC = 0.5        # Polyak-Ruppert: average the iterates of the last 50%


def spsa(theta0, batch_size, n_iter=N_ITER, seed=SEED):
    """Minimise E[penalised_cost] over the box [0, PUMP_MAX]^T.

    Gradient estimate per iteration (Delta ~ Rademacher, so 1/Delta = Delta):
        g_hat = (F(theta + c_k Delta) - F(theta - c_k Delta)) / (2 c_k) * Delta
    with F averaged over `batch_size` inflow realisations, the SAME
    realisations for both evaluations (common random numbers).

    The objective is nearly flat in how pumping is spread over the horizon
    (the storage buffers timing differences) and the exponential inflow has
    a heavy right tail, so the last iterate keeps rattling around in a flat
    valley. The returned schedule is therefore the Polyak-Ruppert average
    of the final AVG_FRAC of the iterates instead of the last iterate.
    """
    rng = np.random.default_rng(seed)
    theta = np.asarray(theta0, dtype=float).copy()

    theta_hist = np.empty((n_iter + 1, T))
    theta_hist[0] = theta
    cost_hist = np.empty(n_iter)

    for k in range(n_iter):
        a_k = SPSA_a / (k + 1 + SPSA_A) ** ALPHA
        c_k = SPSA_c / (k + 1) ** GAMMA

        delta = rng.choice([-1.0, 1.0], size=T)
        q_in_batch = sample_inflow(rng, batch_size)

        theta_plus = np.clip(theta + c_k * delta, 0.0, PUMP_MAX)
        theta_minus = np.clip(theta - c_k * delta, 0.0, PUMP_MAX)

        f_plus = np.mean([penalised_cost(theta_plus, q) for q in q_in_batch])
        f_minus = np.mean([penalised_cost(theta_minus, q) for q in q_in_batch])

        g_hat = (f_plus - f_minus) / (2.0 * c_k) * delta
        theta = np.clip(theta - a_k * g_hat, 0.0, PUMP_MAX)

        theta_hist[k + 1] = theta
        cost_hist[k] = 0.5 * (f_plus + f_minus)

    theta_avg = theta_hist[int((1.0 - AVG_FRAC) * n_iter):].mean(axis=0)
    return theta_avg, theta_hist, cost_hist


# ------------------------------------------------------------------
# 4. Monte-Carlo evaluation of a fixed schedule
# ------------------------------------------------------------------
def evaluate(q_pump, n_samples=5000, seed=2026):
    """Out-of-sample estimate of expected cost and violation statistics."""
    rng = np.random.default_rng(seed)
    inflows = sample_inflow(rng, n_samples)
    costs = np.empty(n_samples)
    violated = np.empty(n_samples, dtype=bool)
    for i, q_in in enumerate(inflows):
        H = simulate_storage(q_pump, q_in)
        costs[i] = penalised_cost(q_pump, q_in)
        violated[i] = np.any(H > STORAGE_MAX) or np.any(H < 0.0)
    return {
        'pumped volume (m3)': np.sum(q_pump) * dt,
        'E[penalised cost]': costs.mean(),
        'P(bound violated)': violated.mean(),
    }


# ------------------------------------------------------------------
# 5. Run for batch sizes 1, 2, 4 and compare
# ------------------------------------------------------------------
if __name__ == '__main__':
    RTC_REF = ('/Users/martijnkrikke/Documents/Scriptie/rtc-tools/examples/'
               'mixed_integer/reference_output/timeseries_export.csv')
    theta0 = pd.read_csv(RTC_REF)['Q_pump'].to_numpy()[:T]  # RTC-Tools reference schedule
    batch_sizes = [1, 2, 4]

    results = {}
    for B in batch_sizes:
        theta_f, theta_hist, cost_hist = spsa(theta0, batch_size=B)
        results[B] = {'theta': theta_f, 'hist': theta_hist, 'cost': cost_hist}
        print(f"batch size {B}: averaged schedule "
              f"sum = {theta_f.sum():.2f} m3/s, "
              f"Q_pump = {np.round(theta_f, 2)}")

    # --- out-of-sample comparison, incl. the naive and (if available) the
    #     deterministic MIP schedule, to show what OptiChat's deterministic
    #     answer misses under random inflow ---
    schedules = {'initial (RTC-Tools ref)': theta0}
    try:
        det = pd.read_csv(f'{BASE}/output_results.csv')
        schedules['deterministic MIP'] = det['Q_pump'].to_numpy()[:T]
    except (FileNotFoundError, KeyError):
        pass
    for B in batch_sizes:
        schedules[f'SPSA batch {B}'] = results[B]['theta']

    summary = pd.DataFrame({name: evaluate(q) for name, q in schedules.items()}).T
    print("\nOut-of-sample evaluation (5000 inflow realisations):")
    print(summary.round(3).to_string())

    # ------------------------------------------------------------------
    # 6. Convergence plots
    # ------------------------------------------------------------------
    colors = {1: '#2a78d6', 2: "#af1b1bff", 4: '#eda100'}   # fixed per batch size
    ink, muted, grid = '#0b0b0b', '#52514e', '#e1e0d9'

    fig, (ax0, ax1) = plt.subplots(1, 2, figsize=(12, 4.5))
    fig.patch.set_facecolor('#fcfcfb')

    ma_window = 500
    for B in batch_sizes:
        total = results[B]['hist'].sum(axis=1)
        ax0.plot(total, color=colors[B], lw=1, alpha=0.3)
        moving_avg = np.convolve(total, np.ones(ma_window) / ma_window,
                                 mode='valid')
        ax0.plot(np.arange(ma_window - 1, total.size), moving_avg,
                 color=colors[B], lw=2, label=f'batch size {B}')
    ax0.axhline(theta0.sum(), color=muted, lw=1, ls='--', label='initial (RTC-Tools ref)')
    ax0.set_xlabel('SPSA iteration', color=muted)
    ax0.set_ylabel(r'scheduled pumping  $\sum_t Q_{pump,t}$  (m$^3$/s)', color=muted)
    ax0.set_title('Convergence of the SPSA iterate', color=ink)

    hours = np.arange(1, T + 1)
    ax1.step(hours, theta0, where='mid', color=muted, lw=1, ls='--',
             label='initial (RTC-Tools ref)')
    for B in batch_sizes:
        ax1.step(hours, results[B]['theta'], where='mid',
                 color=colors[B], lw=2, label=f'batch size {B}')
    ax1.set_xlabel('time step t (h)', color=muted)
    ax1.set_ylabel(r'$Q_{pump,t}$  (m$^3$/s)', color=muted)
    ax1.set_title('Final pumping schedules', color=ink)
    ax1.set_xticks(hours[::2])

    for ax in (ax0, ax1):
        ax.set_facecolor('#fcfcfb')
        ax.grid(True, color=grid, lw=0.8)
        ax.set_axisbelow(True)
        for side in ('top', 'right'):
            ax.spines[side].set_visible(False)
        for side in ('left', 'bottom'):
            ax.spines[side].set_color('#c3c2b7')
        ax.tick_params(colors=muted)
        ax.legend(frameon=False, labelcolor=ink)

    fig.tight_layout()
    fig.savefig(f'{BASE}/spsa_convergence.png', dpi=150,
                facecolor=fig.get_facecolor())
    plt.show()
